create-cost: 50000
point-cost: 100000
max-clan-level: 10
# Use PureChat!
clan-chat-format: "§l§6[§bClan§6]§c ({clan_rank_name})§a {user_name} §d>> "
rank:
  1:
    name: "Thành Viên"
    control:
      kick: false
      invite: false
      requestcontrol: false
      setmotd: false
      setrank: false
      levelup: false
  2:
    name: "Phó Clan"
    control:
      kick: true
      invite: true
      requestcontrol: true
      setmotd: true
      setrank: true
      levelup: false
  3:
    name: "Chủ Clan"
    control:
      kick: true
      invite: true
      requestcontrol: true
      setmotd: true
      setrank: true
      levelup: true
settings:
  max_players:
  - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
  - 36
  - 40
  required_points:
  - 0
  - 1000
  - 2000
  - 4000
  - 6000
  - 8000
  - 10000
  - 12000
  - 14000
  - 16000
  required_money:
  - 0
  - 10000000
  - 20000000
  - 40000000
  - 80000000
  - 100000000
  - 120000000
  - 140000000
  - 160000000
  - 180000000
  clan_tag:
  - "%s"
  - "%s"
  - "%s"
  - "%s"
  - "%s"
  - "%s"
  - "%s"
  - "%s"
  - "%s"
  - "%s"
