---
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
force-spawn: false
enable-spawn-message: true
enable-aliases: true
teleport-on-death: 1
hub-server:
  enabled: false
  name: External Server
  host: 127.0.0.1
  port: 19132
hub:
  world: khulobby
  X: -819.0891
  "Y": 52.7534
  Z: -767.7379
  Yaw: 126.81716918945312
  Pitch: 62.05860900878906
...
