---
# AutoClearLagg (ACL) Config

# Seconds betweeach clear lagg
seconds: 1000

# Entities to clear
clear:
  items: true
  mobs: false
  xp-orbs: true
  exempt: # Array of entities not to clear
    - Zombie
    - Pig

messages:
  time-left: "§c§l✉ §e§lMáy chủ sẽ dọn item dưới mặt đất sau §a{SECONDS} §egiây"
  entities-cleared: "§c§l✉ §e§lMáy chủ đã dọn được số lượng item dưới đất là : §a{COUNT} §evật phẩm"

# Countdown times
times: [30, 15, 5, 1]
...
